// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed .\ico.png
var resourceIcoPngData []byte
var resourceIcoPng = &fyne.StaticResource{
	StaticName:    ".\\ico.png",
	StaticContent: resourceIcoPngData,
}
